package com.visor.school.attendance.model;

import jakarta.persistence.*;
import java.time.Instant;
import java.time.LocalDate;
import java.util.UUID;

/**
 * Attendance record for a student
 * Supports both direct teacher marking and session-based class leader collection
 */
@Entity
@Table(name = "attendance_records", indexes = {
    @Index(name = "idx_attendance_student_class_date", columnList = "student_id,class_id,date", unique = true),
    @Index(name = "idx_attendance_class", columnList = "class_id"),
    @Index(name = "idx_attendance_date", columnList = "date"),
    @Index(name = "idx_attendance_session", columnList = "session_id"),
    @Index(name = "idx_attendance_collected_by", columnList = "collected_by")
})
public class AttendanceRecord {
    
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    @Column(name = "student_id", nullable = false)
    private UUID studentId;

    @Column(name = "class_id", nullable = false)
    private UUID classId;

    @Column(name = "date", nullable = false)
    private LocalDate date;

    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false)
    private AttendanceStatus status;

    @Column(name = "marked_by")
    private UUID markedBy; // Teacher ID (direct marking)

    @Column(name = "collected_by")
    private UUID collectedBy; // Student ID (class leader, session-based)

    @Column(name = "session_id")
    private UUID sessionId; // AttendanceSession ID (session-based)

    @Column(name = "approved_by")
    private UUID approvedBy; // Teacher ID (who approved the session)

    @Column(name = "notes", columnDefinition = "TEXT")
    private String notes;

    @Column(name = "marked_at", nullable = false)
    private Instant markedAt;

    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    @Version
    @Column(name = "version", nullable = false)
    private Long version;

    @Column(name = "updated_by")
    private UUID updatedBy;

    // Default constructor for JPA
    protected AttendanceRecord() {
        // ID is generated by JPA
        this.markedAt = Instant.now();
        this.updatedAt = Instant.now();
        this.version = 0L;
    }

    // Constructor for direct marking
    public AttendanceRecord(UUID studentId, UUID classId, LocalDate date, 
                           AttendanceStatus status, UUID markedBy) {
        this();
        this.studentId = studentId;
        this.classId = classId;
        this.date = date;
        this.status = status;
        this.markedBy = markedBy;
        validate();
    }

    // Constructor for session-based collection
    public AttendanceRecord(UUID studentId, UUID classId, LocalDate date,
                           AttendanceStatus status, UUID collectedBy, UUID sessionId) {
        this();
        this.studentId = studentId;
        this.classId = classId;
        this.date = date;
        this.status = status;
        this.collectedBy = collectedBy;
        this.sessionId = sessionId;
        validate();
    }

    // Full constructor
    public AttendanceRecord(UUID studentId, UUID classId, LocalDate date,
                           AttendanceStatus status, UUID markedBy, UUID collectedBy,
                           UUID sessionId, UUID approvedBy, String notes) {
        this();
        this.studentId = studentId;
        this.classId = classId;
        this.date = date;
        this.status = status;
        this.markedBy = markedBy;
        this.collectedBy = collectedBy;
        this.sessionId = sessionId;
        this.approvedBy = approvedBy;
        this.notes = notes;
        validate();
    }

    private void validate() {
        if (date.isAfter(LocalDate.now())) {
            throw new IllegalArgumentException("Attendance date cannot be in the future");
        }

        // Validation: Either direct marking OR session-based collection
        boolean isDirectMarking = markedBy != null && collectedBy == null && sessionId == null;
        boolean isSessionBased = markedBy == null && collectedBy != null && sessionId != null;
        
        if (!isDirectMarking && !isSessionBased) {
            throw new IllegalArgumentException(
                "Attendance record must be either direct marking (markedBy) or session-based (collectedBy + sessionId)"
            );
        }

        // If session-based, collectedBy must be set
        if (sessionId != null && collectedBy == null) {
            throw new IllegalArgumentException("If sessionId is provided, collectedBy must be set");
        }

        // If approvedBy is set, sessionId must be provided
        if (approvedBy != null && sessionId == null) {
            throw new IllegalArgumentException("If approvedBy is set, sessionId must be provided");
        }
    }

    public void updateStatus(AttendanceStatus newStatus, UUID updatedBy, String notes) {
        this.status = newStatus;
        this.updatedBy = updatedBy;
        this.notes = notes;
        this.updatedAt = Instant.now();
    }

    public boolean isDirectMarking() {
        return markedBy != null && sessionId == null;
    }

    public boolean isSessionBased() {
        return sessionId != null && collectedBy != null;
    }

    // Getters and Setters
    public UUID getId() {
        return id;
    }

    public UUID getStudentId() {
        return studentId;
    }

    public UUID getClassId() {
        return classId;
    }

    public LocalDate getDate() {
        return date;
    }

    public AttendanceStatus getStatus() {
        return status;
    }

    public void setStatus(AttendanceStatus status) {
        this.status = status;
    }

    public UUID getMarkedBy() {
        return markedBy;
    }

    public UUID getCollectedBy() {
        return collectedBy;
    }

    public UUID getSessionId() {
        return sessionId;
    }

    public UUID getApprovedBy() {
        return approvedBy;
    }

    public String getNotes() {
        return notes;
    }

    public void setNotes(String notes) {
        this.notes = notes;
    }

    public Instant getMarkedAt() {
        return markedAt;
    }

    public Instant getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(Instant updatedAt) {
        this.updatedAt = updatedAt;
    }

    public Long getVersion() {
        return version;
    }

    public UUID getUpdatedBy() {
        return updatedBy;
    }

    public void setUpdatedBy(UUID updatedBy) {
        this.updatedBy = updatedBy;
    }
}
