-- Config Server database schema for encrypted configuration storage
CREATE TABLE IF NOT EXISTS CONFIG_PROPERTIES (
    ID BIGSERIAL PRIMARY KEY,
    APPLICATION VARCHAR(255) NOT NULL,
    PROFILE VARCHAR(255) NOT NULL,
    LABEL VARCHAR(255) NOT NULL,
    KEY VARCHAR(255) NOT NULL,
    VALUE TEXT NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(APPLICATION, PROFILE, LABEL, KEY)
);

CREATE INDEX IF NOT EXISTS IDX_CONFIG_PROPERTIES_APP_PROFILE_LABEL 
    ON CONFIG_PROPERTIES(APPLICATION, PROFILE, LABEL);

