-- Insert user-service configuration into Config Server
-- APPLICATION: user-service, PROFILE: default, LABEL: master

INSERT INTO CONFIG_PROPERTIES (APPLICATION, PROFILE, LABEL, KEY, VALUE) VALUES
('user-service', 'default', 'master', 'server.port', '8081'),
('user-service', 'default', 'master', 'spring.datasource.url', 'jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}'),
('user-service', 'default', 'master', 'spring.datasource.username', '${DB_USERNAME}'),
('user-service', 'default', 'master', 'spring.datasource.password', '${DB_PASSWORD}'),
('user-service', 'default', 'master', 'spring.datasource.driver-class-name', 'org.postgresql.Driver'),
('user-service', 'default', 'master', 'spring.jpa.hibernate.ddl-auto', 'validate'),
('user-service', 'default', 'master', 'spring.jpa.show-sql', '${JPA_SHOW_SQL}'),
('user-service', 'default', 'master', 'spring.jpa.properties.hibernate.dialect', 'org.hibernate.dialect.PostgreSQLDialect'),
('user-service', 'default', 'master', 'spring.jpa.properties.hibernate.format_sql', '${HIBERNATE_FORMAT_SQL}'),
('user-service', 'default', 'master', 'spring.flyway.enabled', 'true'),
('user-service', 'default', 'master', 'spring.flyway.locations', 'classpath:db/migration'),
('user-service', 'default', 'master', 'spring.flyway.baseline-on-migrate', '${FLYWAY_BASELINE_ON_MIGRATE}'),
('user-service', 'default', 'master', 'spring.rabbitmq.host', '${RABBITMQ_HOST}'),
('user-service', 'default', 'master', 'spring.rabbitmq.port', '${RABBITMQ_PORT}'),
('user-service', 'default', 'master', 'spring.rabbitmq.username', '${RABBITMQ_USER}'),
('user-service', 'default', 'master', 'spring.rabbitmq.password', '${RABBITMQ_PASSWORD}'),
('user-service', 'default', 'master', 'spring.security.oauth2.resourceserver.jwt.issuer-uri', '${KEYCLOAK_SERVER_URL}/realms/${KEYCLOAK_REALM}'),
('user-service', 'default', 'master', 'eureka.client.service-url.defaultZone', '${DISCOVERY_SERVER_URL}/eureka/'),
('user-service', 'default', 'master', 'eureka.instance.prefer-ip-address', 'true'),
('user-service', 'default', 'master', 'eureka.instance.ip-address', '${EUREKA_INSTANCE_IP}'),
('user-service', 'default', 'master', 'keycloak.realm', '${KEYCLOAK_REALM}'),
('user-service', 'default', 'master', 'keycloak.auth-server-url', '${KEYCLOAK_SERVER_URL}'),
('user-service', 'default', 'master', 'keycloak.server-url', '${KEYCLOAK_SERVER_URL}'),
('user-service', 'default', 'master', 'keycloak.service-client-id', '${USER_PROFILE_CLIENT_ID}'),
('user-service', 'default', 'master', 'keycloak.service-client-secret', '${USER_PROFILE_CLIENT_SECRET}'),
('user-service', 'default', 'master', 'keycloak.admin-username', '${KEYCLOAK_ADMIN}'),
('user-service', 'default', 'master', 'keycloak.admin-password', '${KEYCLOAK_ADMIN_PASSWORD}'),
('user-service', 'default', 'master', 'keycloak.admin-client-id', '${KEYCLOAK_ADMIN_CLIENT_ID}'),
('user-service', 'default', 'master', 'management.endpoints.web.exposure.include', 'health,info,prometheus,metrics'),
('user-service', 'default', 'master', 'management.endpoint.health.show-details', 'always'),
('user-service', 'default', 'master', 'management.metrics.export.prometheus.enabled', 'true'),
('user-service', 'default', 'master', 'management.metrics.tags.application', '${spring.application.name}'),
('user-service', 'default', 'master', 'management.metrics.tags.environment', '${ENVIRONMENT}'),
('user-service', 'default', 'master', 'logging.level.com.visor.school', 'DEBUG'),
('user-service', 'default', 'master', 'logging.level.org.springframework.security', 'DEBUG'),
('user-service', 'default', 'master', 'logging.level.org.springframework', 'INFO'),
('user-service', 'default', 'master', 'logging.level.org.springframework.web', 'DEBUG'),
('user-service', 'default', 'master', 'logging.level.root', 'INFO'),
('user-service', 'default', 'master', 'logging.pattern.console', '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] [%X{correlationId}] %-5level %logger{36} - %msg%n'),
('user-service', 'default', 'master', 'logging.pattern.file', '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] [%X{correlationId}] %-5level %logger{36} - %msg%n'),
('user-service', 'default', 'master', 'logging.file.name', 'logs/user-service.log'),
('user-service', 'default', 'master', 'logging.logback.rollingpolicy.file-name-pattern', 'logs/user-service-%d{yyyy-MM-dd}.log'),
('user-service', 'default', 'master', 'logging.logback.rollingpolicy.max-history', '30'),
('user-service', 'default', 'master', 'logging.logback.rollingpolicy.total-size-cap', '1GB'),
('user-service', 'default', 'master', 'default-admin.email', '${DEFAULT_ADMIN_EMAIL}'),
('user-service', 'default', 'master', 'default-admin.password', '${DEFAULT_ADMIN_PASSWORD}'),
('user-service', 'default', 'master', 'default-admin.first-name', '${DEFAULT_ADMIN_FIRSTNAME}'),
('user-service', 'default', 'master', 'default-admin.last-name', '${DEFAULT_ADMIN_LASTNAME}'),
('user-service', 'default', 'master', 'default-admin.phone-number', '${DEFAULT_ADMIN_PHONE}'),
('user-service', 'default', 'master', 'keycloak.initializer.enabled', '${KEYCLOAK_INITIALIZER_ENABLED}'),
('user-service', 'default', 'master', 'keycloak.initializer.admin.url', '${KEYCLOAK_SERVER_URL}'),
('user-service', 'default', 'master', 'keycloak.initializer.admin.username', '${KEYCLOAK_ADMIN}'),
('user-service', 'default', 'master', 'keycloak.initializer.admin.password', '${KEYCLOAK_ADMIN_PASSWORD}'),
('user-service', 'default', 'master', 'keycloak.initializer.admin.client-id', '${KEYCLOAK_ADMIN_CLIENT_ID}'),
('user-service', 'default', 'master', 'keycloak.initializer.retry.max-attempts', '${KEYCLOAK_INITIALIZER_MAX_ATTEMPTS}'),
('user-service', 'default', 'master', 'keycloak.initializer.retry.initial-backoff-millis', '${KEYCLOAK_INITIALIZER_BACKOFF}'),
('user-service', 'default', 'master', 'keycloak.initializer.retry.multiplier', '${KEYCLOAK_INITIALIZER_BACKOFF_MULTIPLIER}'),
('user-service', 'default', 'master', 'keycloak.initializer.retry.fail-on-error', '${KEYCLOAK_INITIALIZER_FAIL_ON_ERROR}')
ON CONFLICT (APPLICATION, PROFILE, LABEL, KEY) DO NOTHING;

