-- Insert keycloak initializer configuration for user-service
-- Moves keycloak.initializer config from application.yml to Config Server
-- APPLICATION: user-service, PROFILE: default, LABEL: master

INSERT INTO CONFIG_PROPERTIES (APPLICATION, PROFILE, LABEL, KEY, VALUE) VALUES
-- Realm
('user-service', 'default', 'master', 'keycloak.initializer.realm.name', '${KEYCLOAK_REALM}'),
('user-service', 'default', 'master', 'keycloak.initializer.realm.enabled', 'true'),
-- Client 0 - public/frontend client
('user-service', 'default', 'master', 'keycloak.initializer.clients[0].client-id', '${USER_PROFILE_CLIENT_ID}'),
('user-service', 'default', 'master', 'keycloak.initializer.clients[0].protocol', 'openid-connect'),
('user-service', 'default', 'master', 'keycloak.initializer.clients[0].public-client', 'false'),
('user-service', 'default', 'master', 'keycloak.initializer.clients[0].service-accounts-enabled', 'true'),
('user-service', 'default', 'master', 'keycloak.initializer.clients[0].redirect-uris[0]', 'http://localhost:8080/*'),
('user-service', 'default', 'master', 'keycloak.initializer.clients[0].redirect-uris[1]', 'https://api.school.visor.com/*'),
('user-service', 'default', 'master', 'keycloak.initializer.clients[0].web-origins[0]', '+'),
('user-service', 'default', 'master', 'keycloak.initializer.clients[0].attributes[access-token-lifespan]', '300'),
('user-service', 'default', 'master', 'keycloak.initializer.clients[0].attributes[client-session-idle-timeout]', '1800'),
('user-service', 'default', 'master', 'keycloak.initializer.clients[0].attributes[client-session-max-lifespan]', '36000'),
-- Client 1 - service account client
('user-service', 'default', 'master', 'keycloak.initializer.clients[1].client-id', '${USER_PROFILE_CLIENT_ID}'),
('user-service', 'default', 'master', 'keycloak.initializer.clients[1].protocol', 'openid-connect'),
('user-service', 'default', 'master', 'keycloak.initializer.clients[1].public-client', 'false'),
('user-service', 'default', 'master', 'keycloak.initializer.clients[1].service-accounts-enabled', 'true'),
('user-service', 'default', 'master', 'keycloak.initializer.clients[1].secret', '${USER_PROFILE_CLIENT_SECRET}'),
('user-service', 'default', 'master', 'keycloak.initializer.clients[1].attributes[access-token-lifespan]', '600'),
-- Realm roles
('user-service', 'default', 'master', 'keycloak.initializer.realm-roles[0].name', 'SUPER_ADMIN'),
('user-service', 'default', 'master', 'keycloak.initializer.realm-roles[0].description', 'Super administrator with full system access including administrator management'),
('user-service', 'default', 'master', 'keycloak.initializer.realm-roles[1].name', 'ADMIN'),
('user-service', 'default', 'master', 'keycloak.initializer.realm-roles[1].description', 'System administrator with full access'),
('user-service', 'default', 'master', 'keycloak.initializer.realm-roles[2].name', 'TEACHER'),
('user-service', 'default', 'master', 'keycloak.initializer.realm-roles[2].description', 'Teacher with class and grade management permissions'),
('user-service', 'default', 'master', 'keycloak.initializer.realm-roles[3].name', 'STUDENT'),
('user-service', 'default', 'master', 'keycloak.initializer.realm-roles[3].description', 'Student with read access to own records'),
('user-service', 'default', 'master', 'keycloak.initializer.realm-roles[4].name', 'PARENT'),
('user-service', 'default', 'master', 'keycloak.initializer.realm-roles[4].description', 'Parent with access to children''s records'),
-- Client roles
('user-service', 'default', 'master', 'keycloak.initializer.client-roles[0].client-id', '${USER_PROFILE_CLIENT_ID}'),
('user-service', 'default', 'master', 'keycloak.initializer.client-roles[0].name', 'COLLECT_ATTENDANCE'),
('user-service', 'default', 'master', 'keycloak.initializer.client-roles[0].description', 'Permission to collect attendance as class leader'),
('user-service', 'default', 'master', 'keycloak.initializer.client-roles[1].client-id', '${USER_PROFILE_CLIENT_ID}'),
('user-service', 'default', 'master', 'keycloak.initializer.client-roles[1].name', 'MANAGE_ATTENDANCE'),
('user-service', 'default', 'master', 'keycloak.initializer.client-roles[1].description', 'Permission to manage attendance records'),
('user-service', 'default', 'master', 'keycloak.initializer.client-roles[2].client-id', '${USER_PROFILE_CLIENT_ID}'),
('user-service', 'default', 'master', 'keycloak.initializer.client-roles[2].name', 'COLLECT_EXAM_RESULTS'),
('user-service', 'default', 'master', 'keycloak.initializer.client-roles[2].description', 'Permission to collect exam results (class teachers grades 7-12)'),
('user-service', 'default', 'master', 'keycloak.initializer.client-roles[3].client-id', '${USER_PROFILE_CLIENT_ID}'),
('user-service', 'default', 'master', 'keycloak.initializer.client-roles[3].name', 'SUBMIT_REPORTS'),
('user-service', 'default', 'master', 'keycloak.initializer.client-roles[3].description', 'Permission to submit reports to school administration'),
('user-service', 'default', 'master', 'keycloak.initializer.client-roles[4].client-id', '${USER_PROFILE_CLIENT_ID}'),
('user-service', 'default', 'master', 'keycloak.initializer.client-roles[4].name', 'VIEW_ALL_STUDENTS'),
('user-service', 'default', 'master', 'keycloak.initializer.client-roles[4].description', 'Permission to view all student records'),
('user-service', 'default', 'master', 'keycloak.initializer.client-roles[5].client-id', '${USER_PROFILE_CLIENT_ID}'),
('user-service', 'default', 'master', 'keycloak.initializer.client-roles[5].name', 'MANAGE_GRADES'),
('user-service', 'default', 'master', 'keycloak.initializer.client-roles[5].description', 'Permission to record and modify grades'),
('user-service', 'default', 'master', 'keycloak.initializer.client-roles[6].client-id', '${USER_PROFILE_CLIENT_ID}'),
('user-service', 'default', 'master', 'keycloak.initializer.client-roles[6].name', 'MANAGE_HOMEROOM'),
('user-service', 'default', 'master', 'keycloak.initializer.client-roles[6].description', 'Permission to manage homeroom class (grades 1-6)'),
('user-service', 'default', 'master', 'keycloak.initializer.client-roles[7].client-id', '${USER_PROFILE_CLIENT_ID}'),
('user-service', 'default', 'master', 'keycloak.initializer.client-roles[7].name', 'MANAGE_ADMINISTRATORS'),
('user-service', 'default', 'master', 'keycloak.initializer.client-roles[7].description', 'Permission to create, update, and manage administrator accounts'),
-- Composites: SUPER_ADMIN
('user-service', 'default', 'master', 'keycloak.initializer.composites[0].realm-role', 'SUPER_ADMIN'),
('user-service', 'default', 'master', 'keycloak.initializer.composites[0].client-id', '${USER_PROFILE_CLIENT_ID}'),
('user-service', 'default', 'master', 'keycloak.initializer.composites[0].client-roles[0]', 'COLLECT_ATTENDANCE'),
('user-service', 'default', 'master', 'keycloak.initializer.composites[0].client-roles[1]', 'MANAGE_ATTENDANCE'),
('user-service', 'default', 'master', 'keycloak.initializer.composites[0].client-roles[2]', 'COLLECT_EXAM_RESULTS'),
('user-service', 'default', 'master', 'keycloak.initializer.composites[0].client-roles[3]', 'SUBMIT_REPORTS'),
('user-service', 'default', 'master', 'keycloak.initializer.composites[0].client-roles[4]', 'VIEW_ALL_STUDENTS'),
('user-service', 'default', 'master', 'keycloak.initializer.composites[0].client-roles[5]', 'MANAGE_GRADES'),
('user-service', 'default', 'master', 'keycloak.initializer.composites[0].client-roles[6]', 'MANAGE_HOMEROOM'),
('user-service', 'default', 'master', 'keycloak.initializer.composites[0].client-roles[7]', 'MANAGE_ADMINISTRATORS'),
-- Composites: ADMIN
('user-service', 'default', 'master', 'keycloak.initializer.composites[1].realm-role', 'ADMIN'),
('user-service', 'default', 'master', 'keycloak.initializer.composites[1].client-id', '${USER_PROFILE_CLIENT_ID}'),
('user-service', 'default', 'master', 'keycloak.initializer.composites[1].client-roles[0]', 'COLLECT_ATTENDANCE'),
('user-service', 'default', 'master', 'keycloak.initializer.composites[1].client-roles[1]', 'MANAGE_ATTENDANCE'),
('user-service', 'default', 'master', 'keycloak.initializer.composites[1].client-roles[2]', 'COLLECT_EXAM_RESULTS'),
('user-service', 'default', 'master', 'keycloak.initializer.composites[1].client-roles[3]', 'SUBMIT_REPORTS'),
('user-service', 'default', 'master', 'keycloak.initializer.composites[1].client-roles[4]', 'VIEW_ALL_STUDENTS'),
('user-service', 'default', 'master', 'keycloak.initializer.composites[1].client-roles[5]', 'MANAGE_GRADES'),
('user-service', 'default', 'master', 'keycloak.initializer.composites[1].client-roles[6]', 'MANAGE_HOMEROOM'),
-- Composites: TEACHER
('user-service', 'default', 'master', 'keycloak.initializer.composites[2].realm-role', 'TEACHER'),
('user-service', 'default', 'master', 'keycloak.initializer.composites[2].client-id', '${USER_PROFILE_CLIENT_ID}'),
('user-service', 'default', 'master', 'keycloak.initializer.composites[2].client-roles[0]', 'MANAGE_ATTENDANCE'),
('user-service', 'default', 'master', 'keycloak.initializer.composites[2].client-roles[1]', 'MANAGE_GRADES')
ON CONFLICT (APPLICATION, PROFILE, LABEL, KEY) DO NOTHING;
