openapi: 3.0.3
info:
  title: Attendance Service API
  description: API for daily attendance tracking and reporting
  version: 1.0.0

servers:
  - url: http://localhost:8081/api/v1
    description: Local development
  - url: https://api.schoolmanagement.edu/attendance-service/api/v1
    description: Production

tags:
  - name: Attendance
    description: Attendance marking and management
  - name: Reports
    description: Attendance reports

paths:
  /attendance:
    post:
      tags:
        - Attendance
      summary: Mark attendance for students
      description: Teacher marks attendance for multiple students in a class
      operationId: markAttendance
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MarkAttendanceRequest'
      responses:
        '201':
          description: Attendance marked successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AttendanceRecordResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /attendance/{attendanceId}:
    put:
      tags:
        - Attendance
      summary: Update attendance record
      description: Correct an attendance record (maintains audit trail)
      operationId: updateAttendance
      security:
        - BearerAuth: []
      parameters:
        - name: attendanceId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateAttendanceRequest'
      responses:
        '200':
          description: Attendance updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AttendanceRecordResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          description: Attendance record not found
        '500':
          $ref: '#/components/responses/InternalServerError'

  /attendance/class/{classId}:
    get:
      tags:
        - Attendance
      summary: Get attendance for a class
      description: Retrieve attendance records for a specific class and date
      operationId: getClassAttendance
      security:
        - BearerAuth: []
      parameters:
        - name: classId
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: date
          in: query
          required: true
          schema:
            type: string
            format: date
      responses:
        '200':
          description: Attendance records
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AttendanceRecordResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          description: Class not found
        '500':
          $ref: '#/components/responses/InternalServerError'

  /attendance/student/{studentId}:
    get:
      tags:
        - Attendance
      summary: Get student attendance history
      description: Retrieve attendance history for a specific student
      operationId: getStudentAttendance
      security:
        - BearerAuth: []
      parameters:
        - name: studentId
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: startDate
          in: query
          schema:
            type: string
            format: date
        - name: endDate
          in: query
          schema:
            type: string
            format: date
        - name: classId
          in: query
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Attendance history
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AttendanceRecordResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          description: Student not found
        '500':
          $ref: '#/components/responses/InternalServerError'

  /reports/class/{classId}:
    get:
      tags:
        - Reports
      summary: Generate class attendance report
      description: Generate attendance report for a class within date range
      operationId: getClassAttendanceReport
      security:
        - BearerAuth: []
      parameters:
        - name: classId
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: startDate
          in: query
          required: true
          schema:
            type: string
            format: date
        - name: endDate
          in: query
          required: true
          schema:
            type: string
            format: date
      responses:
        '200':
          description: Attendance report
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AttendanceReport'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          description: Class not found
        '500':
          $ref: '#/components/responses/InternalServerError'

  /reports/school:
    get:
      tags:
        - Reports
      summary: Generate school-wide attendance report
      description: Generate attendance report for entire school
      operationId: getSchoolAttendanceReport
      security:
        - BearerAuth: []
      parameters:
        - name: startDate
          in: query
          required: true
          schema:
            type: string
            format: date
        - name: endDate
          in: query
          required: true
          schema:
            type: string
            format: date
        - name: gradeLevel
          in: query
          schema:
            type: string
      responses:
        '200':
          description: School-wide attendance report
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SchoolAttendanceReport'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/InternalServerError'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    MarkAttendanceRequest:
      type: object
      required:
        - classId
        - date
        - records
      properties:
        classId:
          type: string
          format: uuid
        date:
          type: string
          format: date
        records:
          type: array
          items:
            $ref: '#/components/schemas/AttendanceRecordInput'

    AttendanceRecordInput:
      type: object
      required:
        - studentId
        - status
      properties:
        studentId:
          type: string
          format: uuid
        status:
          $ref: '#/components/schemas/AttendanceStatus'
        notes:
          type: string

    UpdateAttendanceRequest:
      type: object
      required:
        - status
      properties:
        status:
          $ref: '#/components/schemas/AttendanceStatus'
        notes:
          type: string
          description: Justification for correction

    AttendanceRecordResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        studentId:
          type: string
          format: uuid
        studentName:
          type: string
        classId:
          type: string
          format: uuid
        className:
          type: string
        date:
          type: string
          format: date
        status:
          $ref: '#/components/schemas/AttendanceStatus'
        notes:
          type: string
        markedBy:
          type: string
          format: uuid
        markedAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    AttendanceReport:
      type: object
      properties:
        classId:
          type: string
          format: uuid
        className:
          type: string
        startDate:
          type: string
          format: date
        endDate:
          type: string
          format: date
        totalDays:
          type: integer
        students:
          type: array
          items:
            $ref: '#/components/schemas/StudentAttendanceSummary'
        statistics:
          $ref: '#/components/schemas/AttendanceStatistics'

    StudentAttendanceSummary:
      type: object
      properties:
        studentId:
          type: string
          format: uuid
        studentName:
          type: string
        present:
          type: integer
        absent:
          type: integer
        late:
          type: integer
        excused:
          type: integer
        attendanceRate:
          type: number
          format: float

    AttendanceStatistics:
      type: object
      properties:
        totalStudents:
          type: integer
        averageAttendanceRate:
          type: number
          format: float
        totalPresent:
          type: integer
        totalAbsent:
          type: integer
        totalLate:
          type: integer
        totalExcused:
          type: integer

    SchoolAttendanceReport:
      type: object
      properties:
        startDate:
          type: string
          format: date
        endDate:
          type: string
          format: date
        classes:
          type: array
          items:
            $ref: '#/components/schemas/AttendanceReport'
        overallStatistics:
          $ref: '#/components/schemas/AttendanceStatistics'

    AttendanceStatus:
      type: string
      enum:
        - PRESENT
        - ABSENT
        - LATE
        - EXCUSED

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
        message:
          type: string
        timestamp:
          type: string
          format: date-time
        path:
          type: string

  responses:
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    InternalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

